default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-cocktail-party_development

test:
  <<: *default
  database: rails-cocktail-party_test
